from django.urls import path

from pmo import views

app_name = "pmo"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("portfolios/", views.portfolio_list, name="portfolio_list"),
    path("portfolios/rollup/", views.portfolio_rollup, name="portfolio_rollup"),
    path("portfolios/create/", views.portfolio_create, name="portfolio_create"),
    path("portfolios/<int:portfolio_id>/delete/", views.portfolio_delete, name="portfolio_delete"),
    path("portfolios/assign/", views.portfolio_assign, name="portfolio_assign"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/create/", views.project_create, name="project_create"),
    path("projects/json/", views.projects_json, name="projects_json"),
    path("projects/<int:project_id>/", views.project_detail, name="project_detail"),
    path("projects/<int:project_id>/classic/", views.project_classic, name="project_classic"),
    path("projects/<int:project_id>/board/", views.project_board, name="project_board"),
    path("projects/<int:project_id>/network/", views.project_network, name="project_network"),
    path("projects/<int:project_id>/baseline/set/", views.baseline_set, name="baseline_set"),
    path("projects/<int:project_id>/import-excel/", views.excel_import, name="excel_import"),
    path("projects/<int:project_id>/export-excel/", views.excel_export, name="excel_export"),
    path("projects/<int:project_id>/export-msp/", views.msp_export, name="msp_export"),
    path("projects/<int:project_id>/import-msp/", views.msp_import, name="msp_import"),
    path("projects/<int:project_id>/presence/", views.presence, name="presence"),
    path("projects/<int:project_id>/statuses/save/", views.statuses_save, name="statuses_save"),
    path("projects/<int:project_id>/baselines/save/", views.baseline_save, name="baseline_save"),
    path("projects/<int:project_id>/baselines/<int:baseline_id>/delete/", views.baseline_delete, name="baseline_delete"),
    path("projects/<int:project_id>/resources/save/", views.resource_profile_save, name="resource_profile_save"),
    path("projects/<int:project_id>/level/", views.level_resources, name="level_resources"),
    path("projects/<int:project_id>/fields/create/", views.field_create, name="field_create"),
    path("projects/<int:project_id>/fields/<int:field_id>/delete/", views.field_delete, name="field_delete"),
    path("projects/<int:project_id>/tasks/<int:task_id>/log-time/", views.task_log_time, name="task_log_time"),
    path("projects/<int:project_id>/sprints/create/", views.sprint_create, name="sprint_create"),
    path("projects/<int:project_id>/sprints/<int:sprint_id>/update/", views.sprint_update, name="sprint_update"),
    path("projects/<int:project_id>/sprints/<int:sprint_id>/delete/", views.sprint_delete, name="sprint_delete"),
    path("projects/<int:project_id>/update/", views.project_update, name="project_update"),
    path("projects/<int:project_id>/calendar/update/", views.calendar_update, name="calendar_update"),
    path("projects/<int:project_id>/tasks-data/", views.project_tasks_data, name="project_tasks_data"),
    path("projects/<int:project_id>/tasks/create/", views.task_create, name="task_create"),
    path("projects/<int:project_id>/tasks/create-recurring/", views.task_create_recurring, name="task_create_recurring"),
    path("projects/<int:project_id>/tasks/<int:task_id>/update/", views.task_update, name="task_update"),
    path("projects/<int:project_id>/tasks/<int:task_id>/delete/", views.task_delete, name="task_delete"),
    path("projects/<int:project_id>/tasks/<int:task_id>/reschedule/", views.task_reschedule, name="task_reschedule"),
    path("projects/<int:project_id>/tasks/reorder/", views.task_reorder, name="task_reorder"),
    path("projects/<int:project_id>/raid/", views.raid_list, name="raid_list"),
    path("projects/<int:project_id>/raid/create/", views.raid_create, name="raid_create"),
    path("projects/<int:project_id>/raid/<int:item_id>/update/", views.raid_update, name="raid_update"),
    path("projects/<int:project_id>/raid/<int:item_id>/delete/", views.raid_delete, name="raid_delete"),
    path("portfolios/<int:portfolio_id>/raid/", views.portfolio_raid, name="portfolio_raid"),
    path("raid/", views.raid_overview, name="raid_overview"),
    path("projects/<int:project_id>/timelog/", views.project_timelog, name="project_timelog"),
    path("projects/<int:project_id>/tasks/<int:task_id>/comments/add/", views.task_comment_add, name="task_comment_add"),
    path("projects/<int:project_id>/tasks/<int:task_id>/attachments/add/", views.task_attachment_add, name="task_attachment_add"),
    path("projects/<int:project_id>/tasks/<int:task_id>/attachments/upload/", views.task_attachment_upload, name="task_attachment_upload"),
    path("projects/<int:project_id>/tasks/<int:task_id>/attachments/<int:attachment_id>/delete/", views.task_attachment_delete, name="task_attachment_delete"),
    path("team/", views.team, name="team"),
    path("capabilities/", views.capabilities, name="capabilities"),
    path("team/add/", views.user_add, name="user_add"),
    path("team/<int:user_id>/role/", views.user_role, name="user_role"),
    path("team/<int:user_id>/remove/", views.user_remove, name="user_remove"),
    path("team/assign-project/", views.user_assign_project, name="user_assign_project"),
]
