# Generated by Django 5.1 on 2024-09-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciassociatedservice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assetlist',
        ),
    ]
