# Generated by Django 5.2.16 on 2026-07-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_assignee_sprint_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='baseline_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='baseline_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='constraint_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='constraint_type',
            field=models.CharField(choices=[('ASAP', 'Asap'), ('SNET', 'Snet'), ('MSO', 'Mso')], default='ASAP', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='lag_days',
            field=models.IntegerField(default=0),
        ),
    ]
