# Generated by Django 5.2.16 on 2026-07-20 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_baseline_end_task_baseline_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='format_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'On Hold'), ('DONE', 'Complete')], default='TODO', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='core.user')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
