# Generated by Django 5.2.16 on 2026-07-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_format_json_alter_task_status_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='TODO', max_length=40),
        ),
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Complete')], default='NOT_STARTED', max_length=20)),
                ('color', models.CharField(default='#94a3b8', max_length=9)),
                ('sort_order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
