# Generated by Django 5.2.16 on 2026-07-21 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resourceprofile_resourcetimeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.CharField(choices=[('TRADITIONAL', 'Waterfall / Gantt'), ('AGILE', 'Agile'), ('HYBRID', 'Hybrid')], default='TRADITIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='constraint_type',
            field=models.CharField(choices=[('ASAP', 'As Soon As Possible'), ('ALAP', 'As Late As Possible'), ('SNET', 'Start No Earlier Than'), ('SNLT', 'Start No Later Than'), ('FNET', 'Finish No Earlier Than'), ('FNLT', 'Finish No Later Than'), ('MSO', 'Must Start On'), ('MFO', 'Must Finish On')], default='ASAP', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.FloatField(default=1.0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='core.user')),
            ],
            options={
                'unique_together': {('task', 'user')},
            },
        ),
    ]
