# Generated by Django 5.2.16 on 2026-07-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_methodology_alter_task_constraint_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprofile',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='effort_driven',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='fixed_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduling_mode',
            field=models.CharField(choices=[('AUTO', 'Auto Scheduled'), ('MANUAL', 'Manually Scheduled')], default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('FIXED_UNITS', 'Fixed Units'), ('FIXED_DURATION', 'Fixed Duration'), ('FIXED_WORK', 'Fixed Work')], default='FIXED_UNITS', max_length=20),
        ),
    ]
