# Generated by Django 5.2.16 on 2026-07-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resourceprofile_rate_task_effort_driven_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprofile',
            name='working_days_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
