# Generated by Django 5.1 on 2024-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciassociatedservice', '0002_delete_assetlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assetlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appfiles/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
            ],
        ),
    ]
