# Generated by Django 5.1 on 2024-09-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciassociatedservice', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlist',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='upload_date',
        ),
    ]
