# Generated by Django 5.1 on 2024-09-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciassociatedservice', '0004_remove_assetlist_file_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assetlist',
        ),
    ]
